var new_lang = {
    lt1: 'Ingyenes visszahívás kérés',
    lt2: '«Tinedol» hatás',
    lt3: 'Hatákényság',
    lt4: 'Vélemények',
    lt5: 'Egyszerű módszer a lábgomba, visketés és repedések legyőzésében!',
    lt6: 'Gyógyítja a lábgombát és körmöket',
    lt7: 'Csökkenti a viszketés és hámlását',
    lt8: 'Megszűnteti az izzadást és a szagokat',
    lt9: 'Begyógyítja a talpon kialakult repedéseket',
    lt10: 'ÁRENDEGMÉNY',
    lt11: '-50%',
    lt12: 'Korlátolt mennyiségben kapható!<br>Siessen!<br> Csak <span class="product-how-much"><span class="lastpack">5</span> csomag</span> <br>speciális áron!',
    lt13: 'Az akció végéig fennmaradt idő:',
    lt14: '00',
    lt15: 'óra',
    lt16: '25',
    lt17: 'perc',
    lt18: '59',
    lt19: 'másodperc',
    lt20: 'Teljes ár:',
    lt21: 'Engedményes ár',
    lt22: 'Megrendelem',
    lt23: 'Az adatai védve vannak',
    lt24: 'span class="title2-span1">Úgy gondolja, hogy a gomba Önt elkerülte?</span> Ha észrevett  akárcsak egy tünetet is magán,<br> már ma kezdje el a gyógyjtást<',
    lt25: 'Kellemetlen szag',
    lt26: 'Repedések és hámlás',
    lt27: 'Helytelen köröm forma',
    lt28: 'A köröm színe<br>barnává vagy sárgává válik',
    lt29: 'Barázdák és fehér <br>foltok a körmön',
    lt30: 'Viszkető és égő érzés',
    lt31: 'Hólyagok a talpon',
    lt32: 'Zsibbadó és szúró érzés',
    lt33: 'Helyenkéti bőrkeményedések<br>a talp környékén',
    lt34: 'Mi történik, ha nem gyógyítjuk a talpgombát',
    lt35: 'Statisztikai adatok szerint minden ötödik magyarországi lakos szenved valamilyenféle bőrgomba fertőzéstől.<br> Szűk, zárt cipő, műszálas zokni, szauna, fürdő, uszoda.br> <span class="stage__span1">A nyári időszakban ezekhez még hozzácspódnak a strandok, parkok, ahol is sokan mezítláb járkálnak.<br> Ez mind a talp szörnyű betegségeihez vezet!</span> Stop!',
    lt36: '1. stádium:',
    lt37: '<i></i>Hámlás',
    lt38: '<i></i>Viszketés',
    lt39: '<i></i>Izzadás',
    lt40: '<i></i>Kellemetlen szag',
    lt41: '<i></i>Diszkomfort',
    lt42: '2. stádium:',
    lt43: '<i></i>Körömgomba',
    lt44: '<i></i>Mély repedések<',
    lt45: '<i></i>Erős izzadás és viszketés',
    lt46: '<i></i>Tartós bűz',
    lt47: '<i></i>Sárga, megvastagodott körmök',
    lt48: '<i></i>“Elhalt”,durva bőr',
    lt49: '<i></i>Séta közbeni <br> erős kellemetlen érzés',
    lt50: '3. stádium:',
    lt51: '<i></i>Hámlás és viszketés <br>a lábujjak között',
    lt52: '<i></i>Fekélyes és mély <br>repedések',
    lt53: '<i></i>Fájdalom',
    lt54: '<i></i>Gennyeződés',
    lt55: '<i></i>A köröm elvesztése',
    lt56: '<span class="stage__main-block-span">A talp nem időbeni kezelésével, gyorsan elszaporodhat ez a szörnyen veszélyes betegség!</span><br> Képzeljék el, hogy ezek az Ön lábai! Szeretne ilyen talpakkal büszkélkedni?<br> Úgye, nem!',
    lt57: 'Hogyan hat <span class="title4-span1"> az «Tinedol» kenőcs?</span>',
    lt58: '<span class="work__span1">Folytonos használat mellett, az «Tinedol» megszabadítja rögtön több problémától is.</span> Az összetevőibe tartozó aktív komponensek hatékonyan felveszik a harcot a',
    lt59: 'Gombával',
    lt60: 'Szagokkal',
    lt61: 'Izzadással',
    lt62: 'Repedésekkel',
    lt63: '<span class="consist__text--b">Klimbazol</span> — megállítja az élesztők és gombák szaporodásátó. Megszűnteti a viszketést. Végleges ütést mér a gombákra.',
    lt64: '<span class="consist__text--b">Farnezol</span> — “bekapcsolja” az izzadás ellenfunkciót. Fertőtlenít, szárít és hosszú időre kellemes illatot ajándékoz. <span class="consist__text--b">Propolys </span> erős antibakteriális hatással bír <span class="consist__text--b"> Teafa olaj </span> mélyen behatol a bőralatti hámrétegbe, gyúgyítva ezzel a bőr problémás részeit, hűsítő hatást biztosít és a nehéz munkanap után kialakult kellemetlen szagokat is legyőzi',
    lt65: 'A krém tökéletesen hidratálja és táplálja a lábat, eltűnteti a durva bőrt, anti-hám hatással bír, begyúgyítja a repedéseket.',
    lt66: 'Más krémektől eltérően az „Tinedol” krém egyenletesen eloszlik a talp teljes felületén. Gyorsan beszívódik és sem a ruházaton, sem az ágyhuzaton nem hagy nyomot.',
    lt67: 'A limitált kiadású sorozatba kővirág olajat is hozzáadtak, ami hatékonyan veszi fel a harcot a sebekkel, amit az új cipő okozott a sarkon valamint a keményedésekkel. Kellemes hűs érzést ajándékoz a bőrnek és szükséges megnyugvást egy nehéz nap után.',
    lt68: 'Egyszerű megoldás <br>a gomba, viszketés és repedések megszüntetésére!',
    lt69: 'Hatékonyság már 30 napos «Tinedol» <span class="title6-span1">használat után</span>',
    lt70: 'Eltűnik a <br>láb és körömgomba',
    lt71: 'Irja be az adatait a lenti formába',
    lt72: 'Megszűnik a viszketés és <br>hámlás',
    lt73: 'Kellemes illat',
    lt74: 'A láb nem izzad',
    lt75: 'Begyógyulnak <br>a repedések',
    lt76: 'Vidám és kellemes<br>mozgás',
    lt77: 'Szép, <br> és ápolt lábak',
    lt78: 'HOgyan hasznélujk <span class="title7-span1">az «Tinedol» krémet?</span>',
    lt79: 'Használat előtt szappannal mossa meg és törölje át a lábát. Egy vékony réteget vigyen fel az egész talpra. Minden este alvás előtt 30 napon át.<br> Meglátja, hogy a sarka és talpa rózsaszínűvé változik majd, a bőre pedig egészségesebb!',
    lt80: 'Mivel jobb az „Tinedol” krém a többi antigomba szertől?',
    lt81: 'A gombaölő szerek két fajtára oszthatóak : az első segít, a másik csak haszálat közben hat. Azoknak az embereknek, akik lábgomba-fertőzéssel küzdenek egyfolytában szükségetetik kenegetni magukat mindenféle krémmel, kenőccsel.',
    lt82: 'Az «Tinedol» a gyökereinél oldja meg a problémát. Többszáz klinikai kutatás bebizonyította, hogy ez a szer hatékonyan veszi fel a harcot a láb- és körömgomba ellen.Már az első kúra elvégzése után a gomba örökre eltűnik és nem jön vissza. Ilyen erős hatás a természetes hatúanyagok együttes erejének használásával érhető el.',
    lt83: 'Szakértői vélemény',
    lt84: 'Ez a szer már rég bebizonyította hatékonyságát. A fő erénye – a komplex ápolás. Ha eddig nem is jelent meg az összes tűnet, megéri elkezdeni az „Tinedol” krém használatát már most, megelőzés képpen.A lábgomba nagyon gyorsan szaporodik. Ma gyenge hámlás ls viszketés vehető észre, holnap pedig ebutalást kap egy klinikára és naponta 5-ször antibiotikumot kell majd szednie. Továbbá, a gomba fertőző. Ha Ön vagy valaki Önhöz közeli személy betegeskedik – az azt jelenti, hogy beteg az egész család!',
    lt85: '— Dr. Búza Sándor<br>orvos-bőrgyógyász, a bőrbetegségek doktora – kozmetológus, mikológus.',
    lt86: 'Vélemények',
    lt87: 'Az «Tinedol»  használata előtt mindvégig azt hittem, hogy a bőrgomba, az olyan, mint az egyszerű gomba – idővel eltűnnek, aztán újra jelentkeznek... Kipróbáltam sok más egyéb szert. A tünetek csökkentek el-eltűntek, de a gomba a lábamon megmaradt. Muszáj voltam orvoshoz fordulni és ő az «Tinedol» krémet írta ki nekem. Már fél éve, hogy semmi sem zavar engem.<br>Köszönöm!',
    lt88: 'Marika, Budapest',
    lt89: 'A talpam, mint az újszülötteké! Gyakran járok uszodába. Amikro megtudtam, hogy bőrgombám van nem voltam nagyon meglepve, hiszen a tusolók közösek, a fülkék közösek, a klór nem véd meg a gombától. Na és mit is lehet tenni. Nálunk ott a lányok mind tudják, hogy az «Tinedol» krémtől jobb szer nincs. Kenjük is magunkat mindnyájan!',
    lt90: 'Szandra, Dunakeszi',
    lt91: 'A gomba hozzászokik azokhoz a szerekhez, amelyekkel próbáljátok elpusztítani. A férjemnek szörnyen izzadt a lába és emiatt a gomba sosem hagyta békén. Két minőségi mutató miatt választottuk az «Tinedol» krémet. Mert izzadásra és lábgombára alkották. 3 hónapig kente és segített. Minden abbamaradt!',
    lt92: 'Каtica, Hajdúszoboszló',
    lt93: '',
    title: 'Az «Tinedol» megvásárlása olcsón. Árak, vélemények. Rendelje meg az «Tinedol» krémet most!',
};

function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
};